---
kind: pipeline
type: docker
name: convertpdfs

steps:
  - name: convert pdf script
    image: alpine:latest 
    commands:
    - apk add --no-cache curl bash
    - /bin/sh
    - cd ./docs/markdown/
    - ./../../.drone/convert.sh
  - name: commit push pdfs
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: master
      commit: true
      commit_message: "[CI SKIP] push pdf docs"
      force: true
      key: 
        from_secret: deploy_key
services:
  - name: convert
    image: thecodingmachine/gotenberg:latest
trigger:
  branch:
  - master
  event:
  - push
